# docker-compose.yml
services:
  chatapp:
    build: .
    image: dalairf/nodejs-chat-app:latest   # keep this consistent with Jenkinsfile
    ports:
      - "3700:3700"
    environment:
      - NODE_ENV=production
      - PORT=3700
